# when building as standalone package uncomment line below and set version and build_number to proper values
{% set version = "0.3.0" %}
{% set maboss_version = "0.3.0" %}
{% set build_number = "0" %}
{% set python_version = "3.11" %}
{% set numpy_version = "1.24" %} # 1.21 for 3.7 1.24 for other pythn versions  

package:
  name: cc3d-network-solvers
  version: {{ version }}

about:
  home: https://github.com/sys-bio/roadrunner, https://github.com/sys-bio/antimony, https://github.com/CompuCell3D/CompuCell3DExtensions
  license: MIT

extra:
  maintainers: T.J. Sego, Maciek Swat, Herbert Sauro

source:
  path: ../

build:
  number: {{ build_number }}
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python={{ python_version }}
    - setuptools
    - numpy={{ numpy_version }}

  run:
    - python={{ python_version }}
    - cc3dext_maboss={{ maboss_version }}
    - numpy={{ numpy_version }}

  test:
    - numpy={{ numpy_version }}

test:
  imports:
    - sys
    - roadrunner
    - antimony
