# when building as standalone package uncomment line below and set version and build_number to proper values
{% set version = "0.3.0" %}
{% set maboss_version = "0.3.0" %}
{% set build_number = "0" %}
{% set python_version = "3.7" %}

package:
  name: cc3d-network-solvers
  version: {{ version }}

about:
  home: https://github.com/sys-bio/roadrunner, https://github.com/sys-bio/antimony, https://github.com/CompuCell3D/CompuCell3DExtensions
  license: MIT

extra:
  maintainers: T.J. Sego, Maciek Swat, Herbert Sauro

source:
  path: ../

build:
  number: {{ build_number }}
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python={{ python_version }}
    - setuptools

  run:
    - python={{ python_version }}
    - cc3dext_maboss={{ maboss_version }}

test:
  imports:
    - sys
