#!/bin/bash
# save as ./decompress

echo ""
echo "CompuCell3D: Self Extracting Installer"
echo ""

function printUsage() {
  echo -e "\033[1mUsage:\033[0m"
  echo "$0 [INSTALLATION_DIR] [version - optional]"  
  echo
  echo -e "\033[1mOptions:\033[0m"
  echo "  -h (--help)"

}

#Argument validation
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  printUsage
  exit 1
fi

if [ -z "$1" ]; then
  INSTALLATION_DIR=$HOME/CC3D
#  echo "Please enter installation directory"
#  echo
#  printUsage
#  exit 1
else
  INSTALLATION_DIR=$1
  echo "Installation directory : $INSTALLATION_DIR"

fi



echo "Will use the following installation dir : $INSTALLATION_DIR"
echo "For full command line options pass -h option to the installer script"

#export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`
export TMPDIR=/tmp/extractpayload$RANDOM
mkdir -p $TMPDIR
chmod 700 $TMPDIR

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR

CDIR=`pwd`
cd $TMPDIR
chmod 755 ./installer.sh
./installer.sh $INSTALLATION_DIR

cd $CDIR
rm -rf $TMPDIR

echo "All done"

exit 0

__ARCHIVE_BELOW__
